### ISSUE TITLE
Docker Build Test - Loco failed

### ISSUE THREAD

**Issue by nicos1993** [MyoHub/myochallenge_2023eval#6]
Hi all, 

I am just trying out the evaluation code. I have cloned the evaluation repo and added my authentication token... I am now trying to run the workflow `Docker Build Test - Loco` but it fails at the step of Build the Docker Image as there is no file `docker-compose-Loco-Agent.yml`

The workflow `Submission Loco Deprl` seems to be working as anticipated as I can see something in my private leaderboard.

Thanks, 

Nicos

**Comment by elladyr** [comment]
Hi Nicos,

The github actions for `Docker Build Test - Loco` has been fixed.

Just to reiterate `Docker Build Test - Loco`, and its manipulation equivalent, is to test the building of the docker files without submitting it. The actual submission only occurs when your run the submission workflows (i.e. `Submission Loco Deprl`). When using the `Submission Loco Deprl`, edit the `agent_loco_deprl.py` file to include your policies.

Chun Kwang
